// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DialogSwitchController from "./dialog_switch_controller"
application.register("dialog-switch", DialogSwitchController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import MusicController from "./music_controller"
application.register("music", MusicController)

import GameController from "./game_controller"
application.register("game", GameController)
