meta_product_name: "Wagon Quest"
meta_title: "Wagon Quest - Have fun doing flashcards !"
meta_description: "Discover this game of flashcard battles set in Le Wagon's bootcamp and inspired by Pokemon !"
meta_image: "home.jpg"
